version: '2'
services:
  flask:
    image: webapp-flask
    build:
      context: ./src
      dockerfile: Dockerfile
    privileged: true
    restart: always
  nginx:
    image: webapp-nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 5000:80
    depends_on:
      - flask
    privileged: true
    restart: always
