version: '2'
services:
  flask:
    image: ismybeercold-flask
    build:
      context: ./src
      dockerfile: Dockerfile
    privileged: true
    restart: always
    labels: io.resin.features.kernel-modules: '1'
  # nginx:
  #   image: ismybeercold-nginx
  #   build:
  #     context: ./nginx
  #     dockerfile: Dockerfile
  #   ports:
  #     - 8080:80
  #   depends_on:
  #     - flask
  #   privileged: true
  #   restart: always
